name: brevity
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  flutter_bloc: ^9.1.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  google_sign_in: ^6.3.0
  http: ^1.3.0
  equatable: ^2.0.7
  card_swiper: ^2.0.1
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  url_launcher: ^6.3.1
  intl: ^0.18.1
  gap: ^3.0.0  
  flutter_card_swiper: ^7.0.2
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1
  share_plus: ^10.1.4
  showcaseview: ^4.0.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # MOVED HERE
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:  # CONFIGURATION MUST BE AT ROOT LEVEL
  android: true
  ios: true
  image_path: "assets/logos/applogo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logos/  # Directory containing applogo.png
    - .env